# Generated by Django 4.0.6 on 2022-08-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created',
        ),
    ]
