# Generated by Django 4.0.6 on 2022-08-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_type_post_type_mood_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_post',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
