# Generated by Django 4.0.6 on 2022-08-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vk_social_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
