# Generated by Django 4.0.6 on 2022-08-21 22:45

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_vk_social_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vk_social_link',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[core.utils.validate_vk_link]),
        ),
    ]
