# Generated by Django 4.0.6 on 2022-08-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(height_field=500, upload_to='images/', width_field=500),
        ),
    ]
