# Generated by Django 4.0.6 on 2022-08-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_interest_profile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
