# Generated by Django 4.0.6 on 2022-08-25 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_interest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.interest'),
        ),
    ]
