# Generated by Django 4.0.6 on 2022-08-25 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_interest_title_alter_profile_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.interest'),
        ),
    ]
